const PRODUCT_LOADING = "PRODUCT_LOADING";
const PRODUCT_SUCESS = "PRODUCT_SUCESS";
const PRODUCT_ERROR = "PRODUCT_ERROR";
const CURRENT_PRODUCT_LOADING = "CURRENT_PRODUCT_LOADING";
const CURRENT_PRODUCT_SUCESS = "CURRENT_PRODUCT_SUCESS";
const CURRENT_PRODUCT_ERROR = "CURRENT_PRODUCT_ERROR";

export {PRODUCT_LOADING,PRODUCT_ERROR,PRODUCT_SUCESS,CURRENT_PRODUCT_ERROR,CURRENT_PRODUCT_LOADING,CURRENT_PRODUCT_SUCESS}